services:
  drone-srcb:
    build: .
    environment:
      API_ID: $API_ID  
      API_HASH: $API_HASH  
      TOKEN: $TOKEN 
      START_PIC: $START_PIC
      CHAT: $CHAT
    ports:
      - 8080
    resources:
      cpu: 1000m
      memory: 3Gi
